version: 0.2

phases:
  install:
    commands:
      # No 'cd' command needed here, as the React application is
      # directly in the root of the GitHub repository.
      - echo "Listing repository contents for debugging..."
      - ls -R # This command will list all files and directories recursively
      - echo "Installing Node.js dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the React application using npx..."
      # Changed 'npm run build' to 'npx react-scripts build'
      # 'npx' ensures that 'react-scripts' is found and executed,
      # even if it's only installed locally in node_modules.
      - npx react-scripts build

artifacts:
  files:
    - '**/*' # Include all files in the build output
  # The 'build' folder will be created directly in the root
  # of the cloned repository by 'npm run build'.
  base-directory: build
