version: 0.2

phases:
  install:
    commands:
      # No 'cd' command needed here, as the React application is
      # directly in the root of the GitHub repository.
      - echo "Listing repository contents for debugging (for reference):"
      - ls -R # This command lists all files and directories recursively
      - echo "Installing Node.js dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the React application using npx vite build..."
      # CORRECTED: Using 'npx vite build' for Vite-based React projects.
      # This command will build your application and place the output
      # into the 'dist' directory by default.
      - npx vite build

artifacts:
  files:
    - '**/*' # Include all files in the build output
  # CORRECTED: Vite typically outputs compiled assets to the 'dist' directory.
  base-directory: dist
